[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spirodraw"
dynamic = ["version"]

dependencies = [
 "numpy",
 "matplotlib",
 "click"
]
requires-python = ">= 3.6"

[project.scripts]
spirodraw = "spirodraw:__main__"